#!/usr/bin/env node
/**
 * Vendor FantasyUI into src/ui/fui/ and public/fui/.
 *
 * FantasyUI is consumed by copying source, not by installing a package (that is the
 * library's own prescribed workflow). This script makes that copy reproducible:
 * it resolves each wanted component's transitive component dependencies, preserves
 * the required `core/` + `components/` sibling layout, and regenerates the barrel
 * and stylesheet so they cover exactly what was vendored — nothing more.
 *
 *   npm run vendor:fui
 *   FUI_SRC=/path/to/fantasyuis npm run vendor:fui
 *
 * The demo site is egress-blocked in the remote dev environment; a git clone of
 * https://github.com/justmarvinai/fantasyuis is the source (ARCHITECTURE §2).
 */
import { readFile, writeFile, mkdir, rm, cp, access } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.resolve(ROOT, process.env.FUI_SRC ?? '../justmarvinai/fantasyuis');

const SRC_LIB = path.join(SRC, 'src/lib');
const SRC_ART = path.join(SRC, 'public/fui');
const OUT_LIB = path.join(ROOT, 'src/ui/fui');
const OUT_ART = path.join(ROOT, 'public/fui');

const CORE_FILES = ['component.ts', 'dom.ts', 'assets.ts'];
const STYLE_FILES = ['assets.css', 'base.css', 'theme-stone-vine.css', 'theme-dark-ember.css'];
const GENERATED_BANNER = `/* GENERATED by tools/vendor-fui.mjs — do not edit by hand.
   Vendored from FantasyUI (justmarvinai/fantasyuis). Upstream fixes go upstream. */`;

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/** Follow `import ... from './Other.ts'` edges until the component set is closed. */
async function resolveComponentSet(requested) {
  const resolved = new Set();
  const queue = [...requested];

  while (queue.length > 0) {
    const name = queue.shift();
    if (resolved.has(name)) continue;

    const file = path.join(SRC_LIB, 'components', `${name}.ts`);
    if (!(await exists(file))) {
      throw new Error(
        `Component "${name}" does not exist in ${SRC_LIB}/components. ` +
          `Check the spelling against docs/UI_FANTASYUI_MAP.md.`,
      );
    }
    resolved.add(name);

    const source = await readFile(file, 'utf8');
    for (const match of source.matchAll(/from\s+'\.\/([A-Za-z0-9_]+)\.ts'/g)) {
      const dep = match[1];
      if (!resolved.has(dep)) queue.push(dep);
    }
  }

  return [...resolved].sort();
}

async function main() {
  if (!(await exists(SRC_LIB))) {
    throw new Error(
      `FantasyUI source not found at ${SRC}.\n` +
        `Clone it first:  git clone https://github.com/justmarvinai/fantasyuis ${SRC}\n` +
        `or point FUI_SRC at an existing clone.`,
    );
  }

  const manifest = JSON.parse(await readFile(path.join(ROOT, 'fui.components.json'), 'utf8'));
  const requested = manifest.components ?? [];
  const components = await resolveComponentSet(requested);
  const pulledIn = components.filter((c) => !requested.includes(c));

  // Rebuild from scratch so a component removed from the manifest actually disappears.
  await rm(OUT_LIB, { recursive: true, force: true });
  await mkdir(path.join(OUT_LIB, 'core'), { recursive: true });
  await mkdir(path.join(OUT_LIB, 'components'), { recursive: true });
  await mkdir(path.join(OUT_LIB, 'styles'), { recursive: true });

  for (const file of CORE_FILES) {
    await cp(path.join(SRC_LIB, 'core', file), path.join(OUT_LIB, 'core', file));
  }

  const componentsWithCss = new Set();
  for (const name of components) {
    await cp(
      path.join(SRC_LIB, 'components', `${name}.ts`),
      path.join(OUT_LIB, 'components', `${name}.ts`),
    );
    const css = path.join(SRC_LIB, 'components', `${name}.css`);
    if (await exists(css)) {
      await cp(css, path.join(OUT_LIB, 'components', `${name}.css`));
      componentsWithCss.add(name);
    }
  }

  for (const file of STYLE_FILES) {
    await cp(path.join(SRC_LIB, 'styles', file), path.join(OUT_LIB, 'styles', file));
  }

  // Stylesheet covering exactly the vendored components. Order matters: asset
  // variables, then tokens, then themes, then components (upstream's own rule).
  const componentImports = components
    .filter((name) => componentsWithCss.has(name))
    .map((name) => `@import '../components/${name}.css';`);
  await writeFile(
    path.join(OUT_LIB, 'styles', 'index.css'),
    [
      GENERATED_BANNER,
      '',
      ...STYLE_FILES.map((file) => `@import './${file}';`),
      '',
      ...componentImports,
      '',
    ].join('\n'),
  );

  await writeFile(
    path.join(OUT_LIB, 'index.ts'),
    [
      GENERATED_BANNER.replace(/^\/\* /, '// ')
        .replace(/\s*\*\/$/, '')
        .replace(/\n\s+/g, '\n// '),
      '',
      ...CORE_FILES.map((file) => `export * from './core/${file}';`),
      '',
      ...components.map((name) => `export * from './components/${name}.ts';`),
      '',
    ].join('\n'),
  );

  // The artwork must ship with the game: no runtime CDN, so the build works
  // offline and inside a later Electron package (ARCHITECTURE §6).
  await rm(OUT_ART, { recursive: true, force: true });
  await cp(SRC_ART, OUT_ART, { recursive: true });

  const cdnHits = await findCdnReferences(components);

  console.log(
    `Vendored ${components.length} components (${componentsWithCss.size} with CSS) from ${SRC}`,
  );
  if (pulledIn.length > 0) {
    console.log(`  dependencies pulled in automatically: ${pulledIn.join(', ')}`);
  }
  console.log(`  core: ${CORE_FILES.join(', ')}`);
  console.log(`  art:  ${path.relative(ROOT, OUT_ART)}`);
  if (cdnHits.length > 0) {
    console.log(
      `  note: ${cdnHits.length} file(s) mention the FantasyUI CDN as a default value ` +
        `(${cdnHits.join(', ')}). The app calls setAssetBase('/fui') at boot and the ` +
        `Playwright offline test asserts no external request is ever made.`,
    );
  }

  async function findCdnReferences(names) {
    const files = [
      ...CORE_FILES.map((f) => path.join(OUT_LIB, 'core', f)),
      ...names.map((n) => path.join(OUT_LIB, 'components', `${n}.ts`)),
      ...STYLE_FILES.map((f) => path.join(OUT_LIB, 'styles', f)),
    ];
    const hits = [];
    for (const file of files) {
      if (!(await exists(file))) continue;
      const text = await readFile(file, 'utf8');
      if (text.includes('vercel.app')) hits.push(path.basename(file));
    }
    return hits;
  }
}

main().catch((error) => {
  console.error(`vendor-fui: ${error.message}`);
  process.exitCode = 1;
});
